### ISSUE TITLE
modified fork to allow for access to S3 GovCloud

### ISSUE THREAD

**Issue by jaychris** [ccpgames/pypicloud-tools#1]
Sorry, I am not sure what the right venue is for notifications like this - your tool is super useful, but I have to work in GovCloud.  I forked your project here (https://github.com/jaychris/pypicloud-tools) with minor changes to allow it to work with S3 in GovCloud. 

I don't know if you are interested in a PR or maybe you want to tell me how I did it wrong (which is easily possible).  At any rate, it worked for me so I thought it might be interesting to you.

**Comment by a-tal** [comment]
hey! cool thanks, I'll check this out.

a PR would be grand, from just skimming it now it'd be nice if we could get it to work with both environments/sets of options. shouldn't be that hard :+1:

**Comment by jaychris** [comment]
really, the only change needed was to allow for the connection to specify the AWS region to connect to.  It might a little easier in boto3 and I originally started down that road, but I was in a bit of a hurry yesterday and this ended up being quicker.  I just removed the credentials from the .pypirc file because it seemed more "in pattern" to pick them up from .aws/credentials.  Anyhow, I'll submit a PR and if you have suggestions to make this a better/more generalized solution, I'd welcome them.  Python (and the v2 v v3 war) is relatively new to me.

**Comment by a-tal** [comment]
cool. the reason I was grabbing them from ~/.pypirc is that's more likely to be there than the .aws/credentials file (at least for python devs).

I've merged your PR in a way that supports both use cases now though. thanks again, let me know if that doesn't work for you.

**Comment by jaychris** [comment]
works for me, thanks!
